# Jekyll Configuration
name: Einfachergo
title: Einfachergo
description: Un blog simple de Jekyll
lang: es

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Permalink structure
permalink: /posts/:title/


